In [18]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [22]:
df = pd.read_csv("sample3.csv")
df.head()

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,address_type,city,facility_type,status,resolution_description,resolution_action_updated_date,community_board,police_precinct,borough,open_data_channel_type,park_facility_name,park_borough,intersection_street_1,intersection_street_2,council_district,x_coordinate_state_plane,y_coordinate_state_plane,latitude,longitude,location,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_sbqj_enih,:@computed_region_92fq_4b7q,location_type,landmark,bbl,vehicle_type,descriptor_2,taxi_pick_up_location,closed_date,bridge_highway_name,bridge_highway_direction,bridge_highway_segment
0,68069701,2026-02-22T02:25:55.000,DOT,Department of Transportation,Street Condition,Pothole,11435.0,HILLSIDE AVENUE,HILLSIDE AVENUE,143 STREET,144 STREET,BLOCKFACE,QUEENS,NaN,Open,The Department of Transportation referred this...,2026-02-22T02:25:55.000,08 QUEENS,Precinct 107,QUEENS,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,68064713,2026-02-22T02:18:20.000,DOT,Department of Transportation,Street Condition,Pothole,11427.0,212 STREET,212 STREET,GRAND CENTRAL PKWY EB EN 212 ST,CLEARVIEW EXPRESSWAY,BLOCKFACE,QUEENS,NaN,Open,The Department of Transportation referred this...,2026-02-22T02:18:20.000,13 QUEENS,Precinct 105,QUEENS,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,68062265,2026-02-22T02:16:59.000,DOT,Department of Transportation,Street Condition,Pothole,11428.0,94 AVENUE,94 AVENUE,217 STREET,218 STREET,BLOCKFACE,QUEENS,NaN,Open,The Department of Transportation referred this...,2026-02-22T02:16:59.000,13 QUEENS,Precinct 105,QUEENS,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,68062266,2026-02-22T02:07:47.000,DOT,Department of Transportation,Street Condition,Pothole,11004.0,NaN,NaN,NaN,NaN,INTERSECTION,QUEENS,NaN,Open,The Department of Transportation referred this...,2026-02-22T02:07:47.000,13 QUEENS,Precinct 105,QUEENS,UNKNOWN,Unspecified,QUEENS,76 AVENUE,264 STREET,23.0,1064411.0,212669.0,40.75004,-73.710686,"{""Point"",[-73.710686, 40.75004]}",63.0,3.0,63.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,68070876,2026-02-22T02:07:19.000,DOT,Department of Transportation,Street Condition,Pothole,11004.0,NaN,NaN,NaN,NaN,INTERSECTION,QUEENS,NaN,Open,The Department of Transportation referred this...,2026-02-22T02:07:19.000,13 QUEENS,Precinct 105,QUEENS,UNKNOWN,Unspecified,QUEENS,76 AVENUE,265 STREET,23.0,1064578.0,212866.0,40.75058,-73.710080,"{""Point"",[-73.71008, 40.75058]}",63.0,3.0,63.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.descriptor_2.value_counts()

descriptor_2
NO HEAT                                14
NO HEAT AND NO HOT WATER                9
Not Cleaned by Property Owner           6
Allout                                  4
Location Type: Residential Address      4
Operating Improperly                    3
Cell Phone Use                          2
Out                                     2
Purse                                   2
Cannabis Smoking or Vaping              2
Waste                                   2
BROKEN OR MISSING                       2
Parked In Front Of Fire Hydrant         2
NO HOT WATER                            2
ROACHES                                 2
Wallet                                  1
Street or Sidewalk                      1
Unsafe Driving                          1
Parked In 'No Standing' Area            1
Passing By                              1
Personal Hygiene Inadequate             1
Down                                    1
Refusal to Accept Credit Card           1
Other                                   1
No Food Protection Certificate          1
Street                                  1
WLWP                                    1
NK1                                     1
Highway                                 1
WA1                                     1
FAUCET BROKEN/MISSING/LEAKING           1
SC2                                     1
AT WALL OR CEILING                      1
Rodent Infestation                      1
Tobacco or Hookah Smoking or Vaping     1
NR5                                     1
NR3                                     1
Flying Too Low                          1
NV1                                     1
Sidewalk Blocked                        1
Name: count, dtype: int64

In [23]:
print(df.columns)

Index(['unique_key', 'created_date', 'agency', 'agency_name', 'complaint_type',
       'descriptor', 'incident_zip', 'incident_address', 'street_name',
       'cross_street_1', 'cross_street_2', 'address_type', 'city',
       'facility_type', 'status', 'resolution_description',
       'resolution_action_updated_date', 'community_board', 'police_precinct',
       'borough', 'open_data_channel_type', 'park_facility_name',
       'park_borough', 'intersection_street_1', 'intersection_street_2',
       'council_district', 'x_coordinate_state_plane',
       'y_coordinate_state_plane', 'latitude', 'longitude', 'location',
       ':@computed_region_f5dn_yrer', ':@computed_region_yeji_bk3q',
       ':@computed_region_sbqj_enih', ':@computed_region_92fq_4b7q',
       'location_type', 'landmark', 'bbl', 'vehicle_type', 'descriptor_2',
       'taxi_pick_up_location', 'closed_date', 'bridge_highway_name',
       'bridge_highway_direction', 'bridge_highway_segment'],
      dtype='str')

In [24]:
df.filter([":@computed_region_f5dn_yrer", ":@computed_region_yeji_bk3q", ":@computed_region_sbqj_enih", ":@computed_region_92fq_4b7q"]).head()

,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_sbqj_enih,:@computed_region_92fq_4b7q
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,63.0,3.0,63.0,16.0
4,63.0,3.0,63.0,16.0

In [11]:
import time

def striptime(x):
    try:
        return pd.to_datetime(x)
    except:
        return x

new_df = df.filter(["closed_date", "created_date"]).dropna(axis=0)
closed_date = pd.to_datetime(new_df.closed_date)
created_date = pd.to_datetime(new_df.created_date)
print(closed_date.head())
diff = closed_date - created_date
print(diff.idxmin(), diff.min())
closed_date[diff.idxmin()], created_date[diff.idxmin()]

0   2021-11-03 17:47:09
1   2021-11-05 16:39:35
2   2021-11-04 00:00:00
3   2021-11-02 14:11:54
4   2021-11-29 07:04:21
Name: closed_date, dtype: datetime64[us]
2405 -114 days +23:59:00

(Timestamp('2021-07-13 10:25:00'), Timestamp('2021-11-03 10:26:00'))

In [49]:
agency_cts = df.agency.value_counts()
complaint_cts = df.complaint_type.value_counts()
print(agency_cts, complaint_cts)

agency
NYPD     37560
HPD      26544
DSNY     13981
DOT       5704
DEP       4458
DOB       2577
DOHMH     2499
DPR       2480
DHS       1877
TLC        811
EDC        771
DCWP       596
OSE         80
DOE         43
DFTA        10
DOITT        9
Name: count, dtype: int64 complaint_type
HEAT/HOT WATER                         13098
Illegal Parking                        11430
Noise - Residential                     8858
Request Large Bulky Item Collection     7051
Blocked Driveway                        5288
                                       ...
Overflowing Litter Baskets                 1
DEP Street Condition                       1
Mosquitoes                                 1
Vacant Lot                                 1
Food Poisoning                             1
Name: count, Length: 165, dtype: int64

In [45]:
location_df = df.filter(['latitude','longitude'])
location_df.isna().value_counts()

latitude  longitude
False     False        983
True      True          17
Name: count, dtype: int64

In [46]:
df.groupby(['borough']).complaint_type.value_counts().reset_index()

   borough                           complaint_type  count
0   QUEENS                       Indoor Air Quality    369
1   QUEENS                           Food Poisoning    128
2   QUEENS                 Traffic Signal Condition     85
3   QUEENS                             Building/Use     60
4   QUEENS                     UNSANITARY CONDITION     40
5   QUEENS                       Noise - Helicopter     32
6   QUEENS                           Taxi Complaint     26
7   QUEENS                                 Asbestos     22
8   QUEENS                          Dead/Dying Tree     21
9   QUEENS                            PAINT/PLASTER     17
10  QUEENS                                 PLUMBING     17
11  QUEENS            General Construction/Plumbing     16
12  QUEENS                                     Mold     16
13  QUEENS                                  GENERAL     15
14  QUEENS                             Damaged Tree     15
15  QUEENS                                APPLIANCE     11
16  QUEENS                  Overgrown Tree/Branches     11
17  QUEENS                               WATER LEAK      9
18  QUEENS                   Street Light Condition      9
19  QUEENS               For Hire Vehicle Complaint      9
20  QUEENS                                   SAFETY      8
21  QUEENS                              DOOR/WINDOW      6
22  QUEENS                      Illegal Tree Damage      6
23  QUEENS                                 ELECTRIC      5
24  QUEENS      Request Large Bulky Item Collection      5
25  QUEENS  Special Projects Inspection Team (SPIT)      5
26  QUEENS                           Uprooted Stump      4
27  QUEENS                  Maintenance or Facility      4
28  QUEENS                          FLOORING/STAIRS      3
29  QUEENS                           HEAT/HOT WATER      3
30  QUEENS                    Street Sign - Missing      3
31  QUEENS                                 Plumbing      2
32  QUEENS            Root/Sewer/Sidewalk Condition      2
33  QUEENS                                    Sewer      2
34  QUEENS                               Electrical      1
35  QUEENS                                 Elevator      1
36  QUEENS                    Street Sign - Damaged      1
37  QUEENS                       Sidewalk Condition      1
38  QUEENS                                 ELEVATOR      1
39  QUEENS                     Green Taxi Complaint      1
40  QUEENS                                   Rodent      1
41  QUEENS            Emergency Response Team (ERT)      1
42  QUEENS                         Dirty Conditions      1
43  QUEENS               Homeless Person Assistance      1
44  QUEENS                             Water System      1
45  QUEENS                     Sanitation Condition      1
46  QUEENS                       School Maintenance      1
47  QUEENS                      Wood Pile Remaining      1