In [9]:
import pandas as pd
import polars as pl
pd.set_option('display.max_columns', None)

In [14]:
df = pl.read_csv("sample_norm.csv", try_parse_dates=True)
df.head()

shape: (5, 44)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ unique_key ┆ created_da ┆ closed_dat ┆ agency ┆ … ┆ road_ramp ┆ vehicle_t ┆ taxi_comp ┆ due_date │
│ ---        ┆ te         ┆ e          ┆ ---    ┆   ┆ ---       ┆ ype       ┆ any_borou ┆ ---      │
│ i64        ┆ ---        ┆ ---        ┆ str    ┆   ┆ str       ┆ ---       ┆ gh        ┆ str      │
│            ┆ datetime[μ ┆ datetime[μ ┆        ┆   ┆           ┆ str       ┆ ---       ┆          │
│            ┆ s]         ┆ s]         ┆        ┆   ┆           ┆           ┆ str       ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 68069701   ┆ 2026-02-22 ┆ null       ┆ DOT    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│            ┆ 02:25:55   ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
│ 68064713   ┆ 2026-02-22 ┆ null       ┆ DOT    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│            ┆ 02:18:20   ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
│ 68062265   ┆ 2026-02-22 ┆ null       ┆ DOT    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│            ┆ 02:16:59   ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
│ 68062266   ┆ 2026-02-22 ┆ null       ┆ DOT    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│            ┆ 02:07:47   ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
│ 68070876   ┆ 2026-02-22 ┆ null       ┆ DOT    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│            ┆ 02:07:19   ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
import time

def striptime(x):
    try:
        return pd.to_datetime(x)
    except:
        return x

df["closed_date_time"] = pl.to_datetime(df.closed_date, errors="coerce")
df["created_date_time"] = pl.to_datetime(df.created_date, errors="coerce")

df.closed_date.is_null().sum()

AttributeError: module 'polars' has no attribute 'to_datetime'

In [49]:
agency_cts = df.agency.value_counts()
complaint_cts = df.complaint_type.value_counts()
print(agency_cts, complaint_cts)

agency
NYPD     37560
HPD      26544
DSNY     13981
DOT       5704
DEP       4458
DOB       2577
DOHMH     2499
DPR       2480
DHS       1877
TLC        811
EDC        771
DCWP       596
OSE         80
DOE         43
DFTA        10
DOITT        9
Name: count, dtype: int64 complaint_type
HEAT/HOT WATER                         13098
Illegal Parking                        11430
Noise - Residential                     8858
Request Large Bulky Item Collection     7051
Blocked Driveway                        5288
                                       ...
Overflowing Litter Baskets                 1
DEP Street Condition                       1
Mosquitoes                                 1
Vacant Lot                                 1
Food Poisoning                             1
Name: count, Length: 165, dtype: int64

In [45]:
location_df = df.filter(['latitude','longitude'])
location_df.isna().value_counts()

latitude  longitude
False     False        983
True      True          17
Name: count, dtype: int64

In [46]:
df.groupby(['borough']).complaint_type.value_counts().reset_index()

   borough                           complaint_type  count
0   QUEENS                       Indoor Air Quality    369
1   QUEENS                           Food Poisoning    128
2   QUEENS                 Traffic Signal Condition     85
3   QUEENS                             Building/Use     60
4   QUEENS                     UNSANITARY CONDITION     40
5   QUEENS                       Noise - Helicopter     32
6   QUEENS                           Taxi Complaint     26
7   QUEENS                                 Asbestos     22
8   QUEENS                          Dead/Dying Tree     21
9   QUEENS                            PAINT/PLASTER     17
10  QUEENS                                 PLUMBING     17
11  QUEENS            General Construction/Plumbing     16
12  QUEENS                                     Mold     16
13  QUEENS                                  GENERAL     15
14  QUEENS                             Damaged Tree     15
15  QUEENS                                APPLIANCE     11
16  QUEENS                  Overgrown Tree/Branches     11
17  QUEENS                               WATER LEAK      9
18  QUEENS                   Street Light Condition      9
19  QUEENS               For Hire Vehicle Complaint      9
20  QUEENS                                   SAFETY      8
21  QUEENS                              DOOR/WINDOW      6
22  QUEENS                      Illegal Tree Damage      6
23  QUEENS                                 ELECTRIC      5
24  QUEENS      Request Large Bulky Item Collection      5
25  QUEENS  Special Projects Inspection Team (SPIT)      5
26  QUEENS                           Uprooted Stump      4
27  QUEENS                  Maintenance or Facility      4
28  QUEENS                          FLOORING/STAIRS      3
29  QUEENS                           HEAT/HOT WATER      3
30  QUEENS                    Street Sign - Missing      3
31  QUEENS                                 Plumbing      2
32  QUEENS            Root/Sewer/Sidewalk Condition      2
33  QUEENS                                    Sewer      2
34  QUEENS                               Electrical      1
35  QUEENS                                 Elevator      1
36  QUEENS                    Street Sign - Damaged      1
37  QUEENS                       Sidewalk Condition      1
38  QUEENS                                 ELEVATOR      1
39  QUEENS                     Green Taxi Complaint      1
40  QUEENS                                   Rodent      1
41  QUEENS            Emergency Response Team (ERT)      1
42  QUEENS                         Dirty Conditions      1
43  QUEENS               Homeless Person Assistance      1
44  QUEENS                             Water System      1
45  QUEENS                     Sanitation Condition      1
46  QUEENS                       School Maintenance      1
47  QUEENS                      Wood Pile Remaining      1